# Build Configurations, if you modify anything here, make sure to modify
# the parser (rim_common/src/types/build_config.rs) as well.

identifier = "xuanwu-rust"

# For GUI
home_page_url = 'https://xuanwu.openatom.cn/'

# Default download sources
rustup_dist_server = 'https://mirror.xuanwu.openatom.cn'
rustup_update_root = 'https://mirror.xuanwu.openatom.cn/rustup'
rim_dist_server = 'https://rust-mirror.obs.cn-north-4.myhuaweicloud.com'
registry = { name = 'xuanwu-sparse', index = 'sparse+https://mirror.xuanwu.openatom.cn/index/' }

[locale.en-US]
logo_text = "XuanWu"
vendor = "Rust China Community"
product = "Rust China Community Distribution"
app_name = "Rust Installation Manager"
content_source = "Content source: Rust China Community, Rust Native Community, Third-party open source community"

[locale.zh-CN]
logo_text = "旋武社区"
vendor = "Rust 中国社区"
product = "Rust 中国社区发行版"
app_name = "Rust 安装管理器"
content_source = "内容来源：Rust 中国社区，Rust 原生社区，第三方开源社区"
